# Databricks App Configuration
# Deploy this app using Databricks Apps

command: [
  "gunicorn",
  "--bind", "0.0.0.0:8000",
  "--workers", "2",
  "--timeout", "300",
  "app:app"
]

env:
  - name: SAMPLE_DATA_LIMIT
    value: "100"

  - name: DQ_GENERATION_JOB_ID
    value: "622090287311428"
