name: "Deploy Databricks Asset Bundle"
description: "Validate and deploy the Databricks bundle for a target environment"
inputs:
  env:
    description: "Environment key (databricks bundle target)"
    required: true
  profile:
    description: "Databricks CLI profile to use"
    required: true
  lakebase-host:
    description: "Lakebase PostgreSQL host for storing DQ rules"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Validate bundle
      shell: bash
      run: |
        set -euxo pipefail
        databricks bundle validate -t "${{ inputs.env }}"

    - name: Configure app.yaml with secrets
      shell: bash
      run: |
        set -euo pipefail
        # Substitute environment-specific values in app.yaml
        if [ -n "${{ inputs.lakebase-host }}" ]; then
          echo "Configuring LAKEBASE_HOST..."
          sed -i 's|\${LAKEBASE_HOST}|${{ inputs.lakebase-host }}|g' app.yaml
        fi
        echo "app.yaml configured"

    - name: Deploy bundle
      shell: bash
      run: |
        set -euxo pipefail
        databricks bundle deploy -t "${{ inputs.env }}"

    - name: Run app (deploy and start)
      shell: bash
      run: |
        set -euxo pipefail
        # Use 'databricks bundle run' to deploy and start the app
        echo "Starting app deployment via bundle run..."
        databricks bundle run dqx_app -t "${{ inputs.env }}"
        echo "App deployment initiated successfully"
