# ============================================================
# HR Onboarding Concierge - Databricks Apps Configuration
# ============================================================

command: [
  "gunicorn", 
  "--bind", "0.0.0.0:8000",
  "--workers", "2",
  "--timeout", "120",
  "app:app"
]

env:
  # Lakebase Instance ID (for OAuth token generation)
  - name: LAKEBASE_INSTANCE_NAME
    value: "backend-database"
  
  # Database Connection Parameters (explicit)
  - name: DB_HOST
    value: "instance-e1c07201-6c30-4306-bbe0-f40d8ebcf2e4.database.cloud.databricks.com"
  - name: DB_USER
    value: "nivethan.venkatachalam@diggibyte.com"
  - name: DB_NAME
    value: "databricks_postgres"
  
  # Knowledge Assistant Agent Endpoint Name
  - name: AGENT_ENDPOINT_NAME
    value: "mas-b705d645-endpoint"
  
  # AI/BI Dashboard Embed URL
  - name: DATABRICKS_DASHBOARD_URL
    value: "https://dbc-425be768-f138.cloud.databricks.com/embed/dashboardsv3/01f0cf060aaa1c14b305d375d6505828?o=1231630146493550"
  
  # Flask secret key
  - name: FLASK_SECRET_KEY
    value: "your-secure-secret-key-change-this"

resources:
  # Lakebase Database Connection
  - name: hr_database
    database:
      instance: "backend-database"
      database: "databricks_postgres"
      permission: "CAN_CONNECT_AND_CREATE"
  
  # Agent Serving Endpoint
  - name: agent_endpoint
    serving_endpoint:
      name: "mas-b705d645-endpoint"
      permission: "CAN_QUERY"